apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  POSTGRES_USER: "postgres"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"

  # REDIS
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"

  # JWT
  JWT_EXPIRES_IN: "7d"

  # USER SERVICE
  USER_SERVICE_PORT: "3001"
  USER_DB_NAME: "users_db"

  # PRODUCT SERVICE
  PRODUCT_SERVICE_PORT: "3002"
  PRODUCT_DB_NAME: "products_db"

  # CART SERVICE
  CART_SERVICE_PORT: "3003"

  # ORDER SERVICE
  ORDER_SERVICE_PORT: "3004"
  ORDER_DB_NAME: "orders_db"

  # PAYMENT SERVICE
  PAYMENT_SERVICE_PORT: "3005"

  # FRONTEND
  NEXT_PUBLIC_API_URL: "http://localhost"
