apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service-deployment
  namespace: ecommerce
  labels:
    app: cart-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
        - name: cart-service
          image: anassehab33/depi-devops-project-cart-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3003
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: CART_SERVICE_PORT
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: REDIS_PORT
